In [ ]:
# cmd view point denoted by ! sign
!pip install numpy
!pip install pandas

In [1]:

# read file using pandas
# pandas is a fast, powerful, flexible and easy to use open source data analysis in python
import pandas as pd
data = pd.read_csv('titanic_short.csv')
### The data read is of type dataframe, which is a 2D data structure where columns can be of different types
type(data)
# tutorial for python data frames: https://stackabuse.com/beginners-tutorial-on-the-pandas-python-library/

pandas.core.frame.DataFrame

In [ ]:
# print using python system print
print(data)

In [ ]:
# print using pandas display
data

In [ ]:
data.head() # we can set the number of first rows to be displayed.
# guess what is the commmand for the tail

In [ ]:
# same goes for tail

# data.tail()

In [ ]:
#### Set specific cells:
data[10:19]

In [ ]:
# self excercise: suggest how to display only survivors (denoted in 1)


In [ ]:
data[data['survived'] == 1]

In [ ]:
# self excercise: suggest how to display only females gender

In [ ]:
data[data['sex']=='female']

In [ ]:
# self excercise: suggest how to display only females survivors

In [ ]:
data[(data['survived'] == 1) & (data['sex']=='female')]

In [ ]:
#### display some of the collumns by a list of collumns
data[ [ 'pclass','age'] ] 

In [ ]:
#### Number of rows and collumns by hsape attribute:
data.shape

In [ ]:
#### Get more information such as the column names by info() method
data.info()

In [ ]:
#### the type of the read data is data frame
type(data)

# set nice equations
### Sphere or Quadratic equations::
$ x^2 + y^2 = z^2 \\$
$ \\ x_1,_2 =  \frac{- b\pm \sqrt{b^2-4ac}}{2a} $

Emphasis, aka italics, with *asterisks* or _underscores_.

Strong emphasis, aka bold, with **asterisks** or __underscores__.

Combined emphasis with **asterisks and _underscores_**.

Strikethrough uses two tildes. ~~Scratch this.~~

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
# . product
print(arr*arr)

[ 1  4  9 16 25]


In [ ]:
#### vector multiplication
arr.dot(arr)
# or by 
arr@arr


In [6]:
# create ones matrix of specific size:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# self excercise: create zeros matrix of specific size:






array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3,2))

In [10]:
# we can create any constant array
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
# self excercise: create a 3X3 matrix where digonal has value of 8






In [12]:
8*np.eye(3)

array([[8., 0., 0.],
       [0., 8., 0.],
       [0., 0., 8.]])

In [13]:
e = np.random.random((2,4)) 
print(e)

[[0.50489847 0.22760998 0.37646776 0.63819532]
 [0.64869039 0.60171157 0.61455719 0.52082071]]


In [15]:
### self learning at home:
# 1. Read the tutorials in links
# 2. Write a NumPy program to test whether none of the elements of a given array is zero (create a sample array).


import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False
